### ISSUE TITLE
Request for you include source code for logout api with Redis

### ISSUE THREAD

**Issue by omudzingwa** [AndresAusecha/spring-security-jwt-redis#1]
Dear Andres,

May you kindly add code for Logout Api where we can use the logout API to invalidate or blacklist the jwt token such that it can not be used again even though it may still be valid.

Note that use off access and refresh tokens will be greatly appreciated. I need help on this because I have been stuck here for a long time.

**Comment by AndresAusecha** [comment]
Hi

Yes, I can, but I do not know whether it's very urgent for you because I do not know when I will be able to do it

**Comment by AndresAusecha** [comment]
heyo @omudzingwa I could not do it before. You can test now the login/logout system. It worked in my tests, also important to mention that this is a experimental project and then I have not done extensive testing, so I suggest to do it first if you're building a enterprise product
